language: java
sudo: false
dist: trusty

script:
  "mvn evosuite:generate"
  "mvn evosuite:export"
  "mvn test"
  "mvn evosuite:info"
  "mvn cobertura:cobertura"
  
after_success:
  - bash <(curl -s https://codecov.io/bash)

